# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XIZoMw_g8OPTDCMOAkzfFLSmaEZoVTlg
"""

from flask import Flask, render_template
import pandas as pd
import plotly.express as px

app = Flask(__name__)

# Load data
df = pd.read_csv("gvsudegree_clean.csv")

df['Graduated'] = pd.to_numeric(df['Graduated'], errors='coerce').fillna(0)

# Clean FIPS
df['stfip'] = (
    pd.to_numeric(df['stfip'], errors='coerce')
    .fillna(0).astype(int).astype(str).str.zfill(2)
)

df['fips'] = (
    pd.to_numeric(df['fips'], errors='coerce')
    .fillna(0).astype(int).astype(str).str.zfill(5)
)

# =====================================================
# ROUTE
# =====================================================
@app.route("/")
def index():

    # NATIONAL MAP
    state_df = df.groupby(['state','stfip'], as_index=False)['Graduated'].sum()

    fig_us = px.choropleth(
        state_df,
        locations='state',
        locationmode='USA-states',
        color='Graduated',
        scope='usa',
        color_continuous_scale='viridis'
    )

    fig_us.update_layout(
        paper_bgcolor='lightgrey',
        plot_bgcolor='lightgrey'
    )

    us_map = fig_us.to_html(full_html=False)

    # MICHIGAN MAP
    mi_df = df[df['stfip'] == '26']
    county_df = mi_df.groupby('fips', as_index=False)['Graduated'].sum()

    fig_mi = px.choropleth(
        county_df,
        geojson="https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json",
        locations='fips',
        color='Graduated',
        scope='usa',
        color_continuous_scale='Blues'
    )

    fig_mi.update_geos(fitbounds="locations", visible=False)

    fig_mi.update_layout(
        paper_bgcolor='lightgrey',
        plot_bgcolor='lightgrey'
    )

    mi_map = fig_mi.to_html(full_html=False)

    # STATE TABLE
    state_table = state_df.sort_values('Graduated', ascending=False)

    # COUNTY TABLE
    county_table = county_df.sort_values('Graduated', ascending=False)

    return render_template(
        "index.html",
        us_map=us_map,
        mi_map=mi_map,
        state_table=state_table.to_html(classes='table'),
        county_table=county_table.to_html(classes='table')
    )

# =====================================================
# RUN
# =====================================================
if __name__ == "__main__":
    app.run(debug=True)