# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KGGMRE3le5EBZtzyehW280sMeXGXyhR4
"""

    
import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(layout="wide")

# =====================================================
# LOAD DATA
# =====================================================
df = pd.read_csv("gvsudegree_clean.csv", low_memory=False)

df['Graduated'] = pd.to_numeric(df['Graduated'], errors='coerce').fillna(0)

df['stfip'] = (
    pd.to_numeric(df['stfip'], errors='coerce')
    .fillna(0).astype(int).astype(str).str.zfill(2)
)

df['fips'] = (
    pd.to_numeric(df['fips'], errors='coerce')
    .fillna(0).astype(int).astype(str).str.zfill(5)
)

us_df = df.copy()
mi_df = df[df['stfip'] == '26'].copy()

# =====================================================
# SIDEBAR (TABLE OF CONTENTS)
# =====================================================
st.sidebar.markdown(
    """
    <div style='background-color:#ADD8E6; padding:20px'>
    <h3 style='text-align:center;'>Table of Contents</h3>
    <ol>
        <li>National Distribution</li>
        <li>Michigan Distribution</li>
        <li>State Level Table</li>
        <li>County Level Table</li>
    </ol>
    </div>
    """,
    unsafe_allow_html=True
)

# =====================================================
# NATIONAL DISTRIBUTION
# =====================================================
st.markdown("<h2 style='text-align:center;'>National Distribution</h2>", unsafe_allow_html=True)

state_df = df.groupby(['state','stfip'], as_index=False)['Graduated'].sum()

fig_us = px.choropleth(
    state_df,
    locations='state',
    locationmode='USA-states',
    color='Graduated',
    scope='usa',
    color_continuous_scale='viridis'
)

fig_us.update_layout(
    paper_bgcolor='lightgrey',
    plot_bgcolor='lightgrey',
    margin=dict(l=10, r=10, t=40, b=10)
)

st.plotly_chart(fig_us, use_container_width=True)

# =====================================================
# MICHIGAN DISTRIBUTION
# =====================================================
st.markdown("<h2 style='text-align:center;'>Michigan Distribution</h2>", unsafe_allow_html=True)

majors = ['All'] + sorted(mi_df['Major'].dropna().unique())
selected_major = st.selectbox("Select Major", majors)

if selected_major == 'All':
    dff = mi_df.copy()
else:
    dff = mi_df[mi_df['Major'] == selected_major]

county_df = dff.groupby('fips', as_index=False)['Graduated'].sum()

fig_mi = px.choropleth(
    county_df,
    geojson="https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json",
    locations='fips',
    color='Graduated',
    color_continuous_scale='Blues',
    scope='usa'
)

fig_mi.update_layout(
    paper_bgcolor='lightgrey',
    plot_bgcolor='lightgrey',
    margin=dict(l=10, r=10, t=40, b=10)
)

fig_mi.update_geos(fitbounds="locations", visible=False)

st.plotly_chart(fig_mi, use_container_width=True)

# =====================================================
# STATE TABLE
# =====================================================
st.markdown("<h2 style='text-align:center;'>State Level Table</h2>", unsafe_allow_html=True)

state_table = us_df.groupby('stfip', as_index=False)['Graduated'].sum()

total = state_table['Graduated'].sum()
state_table['Share of Total'] = (state_table['Graduated']/total*100).round(2)

st.markdown(
    "<div style='background-color:#E6F2FF; padding:10px; border-radius:10px'>",
    unsafe_allow_html=True
)

st.dataframe(
    state_table.sort_values('Graduated', ascending=False),
    use_container_width=True
)

st.markdown("</div>", unsafe_allow_html=True)

# =====================================================
# COUNTY TABLE
# =====================================================
st.markdown("<h2 style='text-align:center;'>County Level Table</h2>", unsafe_allow_html=True)

county_table = county_df.copy()

total = county_table['Graduated'].sum()
county_table['Share of Total'] = (county_table['Graduated']/total*100).round(2)

st.markdown(
    "<div style='background-color:#E6F2FF; padding:10px; border-radius:10px'>",
    unsafe_allow_html=True
)

st.dataframe(
    county_table.sort_values('Graduated', ascending=False),
    use_container_width=True
)

st.markdown("</div>", unsafe_allow_html=True)
